
spring:
  datasource:
    url: jdbc:mysql://192.168.3.6:3306/b_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8030
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    驼峰下划线配置
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*Mapper.xml
